name: px4
channels:
- conda-forge
- defaults
dependencies:
- anaconda-client=1.5.1=py35_0
- autopep8=1.3.1=py35_2
- basemap=1.0.8.dev0=np112py35_3
- blas=1.1=openblas
- bleach=1.5.0=py35_0
- ca-certificates=2017.1.23=0
- cairo=1.14.6=4
- certifi=2017.1.23=py35_0
- clyent=1.2.1=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.10=3
- decorator=4.0.11=py35_0
- entrypoints=0.2.2=py35_1
- expat=2.1.0=2
- ffmpeg=2.8.6=4
- fontconfig=2.12.1=4
- freetype=2.7=1
- geos=3.5.1=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gmp=6.1.2=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- harfbuzz=1.3.4=2
- hdf5=1.8.17=10
- html5lib=0.999=py35_0
- icu=58.1=1
- ipykernel=4.6.1=py35_0
- ipython=5.3.0=py35_0
- ipython_genutils=0.2.0=py35_0
- ipywidgets=6.0.0=py35_0
- jasper=1.900.1=4
- jinja2=2.9.5=py35_0
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=5.0.1=py35_0
- jupyter_console=5.1.0=py35_0
- jupyter_contrib_core=0.3.0=py35_1
- jupyter_contrib_nbextensions=0.2.6=py35_0
- jupyter_core=4.3.0=py35_0
- jupyter_highlight_selected_word=0.0.11=py35_0
- jupyter_latex_envs=1.3.8.2=py35_1
- jupyter_nbextensions_configurator=0.2.4=py35_0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=0
- libsodium=1.0.10=0
- libtiff=4.0.6=7
- libwebp=0.5.2=7
- libxcb=1.12=1
- libxml2=2.9.4=4
- markupsafe=0.23=py35_1
- matplotlib=2.0.0=np112py35_3
- mistune=0.7.4=py35_0
- mpmath=0.19=py35_2
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=5.1.1=py35_1
- nbformat=4.2.0=py35_0
- nbpresent=3.0.2=py35_1
- ncurses=5.9=10
- nose=1.3.7=py35_2
- notebook=5.0.0=py35_0
- numpy=1.12.1=py35_blas_openblas_200
- openblas=0.2.19=1
- opencv=3.2.0=np112py35_blas_openblas_201
- openssl=1.0.2k=0
- pandas=0.19.2=np112py35_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py35_0
- path.py=8.2.1=py35_0
- pcre=8.39=0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=9.0.1=py35_0
- pixman=0.34.0=0
- prompt_toolkit=1.0.14=py35_0
- psutil=5.2.1=py35_0
- ptyprocess=0.5.1=py35_0
- px4tools=0.7.7=py35_0
- pycodestyle=2.3.1=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.2.0=py35_0
- pyproj=1.9.5.1=py35_0
- pyqt=5.6.0=py35_1
- pyshp=1.2.10=py35_0
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytz=2017.2=py35_0
- pyyaml=3.12=py35_1
- pyzmq=16.0.2=py35_1
- qt=5.6.2=1
- qtconsole=4.3.0=py35_0
- readline=6.2=0
- requests=2.13.0=py35_0
- scipy=0.19.0=np112py35_blas_openblas_200
- setuptools=33.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_1
- six=1.10.0=py35_1
- sqlite=3.13.0=1
- sympy=1.0=py35_0
- terminado=0.6=py35_0
- testpath=0.3=py35_0
- tk=8.5.19=1
- tornado=4.4.3=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=2.0.0=py35_0
- x264=20131217=1
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.2=0
- yaml=0.1.6=0
- yapf=0.13.2=py35_0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- _nb_ext_conf=0.3.0=py35_0
- fastcache=1.0.2=py35_1
- jbig=2.1=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mkl=2017.0.1=0
- pip:
  - actionlib==1.11.8
  - bondpy==1.7.18
  - camera-calibration==1.12.19
  - camera-calibration-parsers==1.11.12
  - catkin==0.7.6
  - control==0.7.0
  - controller-manager==0.11.4
  - controller-manager-msgs==0.11.4
  - cv-bridge==1.12.4
  - diagnostic-analysis==1.8.10
  - diagnostic-common-diagnostics==1.8.10
  - diagnostic-updater==1.8.10
  - dynamic-reconfigure==1.5.46
  - gazebo-plugins==2.5.10
  - gazebo-ros==2.5.10
  - gencpp==0.5.5
  - geneus==2.2.5
  - genlisp==0.4.16
  - genmsg==0.5.8
  - gennodejs==2.0.1
  - genpy==0.6.5
  - ghost.py==0.2.3
  - image-geometry==1.12.4
  - interactive-markers==1.11.3
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-contrib-core==0.3.0
  - jupyter-contrib-nbextensions==0.2.6
  - jupyter-core==4.3.0
  - jupyter-highlight-selected-word==0.0.11
  - jupyter-latex-envs==1.3.8.2
  - jupyter-nbextensions-configurator==0.2.4
  - laser-geometry==1.6.4
  - mavros==0.18.7
  - message-filters==1.12.7
  - moveit-commander==0.9.5
  - moveit-ros-planning-interface==0.9.5
  - moveit-ros-visualization==0.9.5
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - nbbrowserpdf==0.2.0
  - pluginlib==1.10.4
  - prompt-toolkit==1.0.14
  - pypdf2==1.26.0
  - python-qt-binding==0.3.2
  - pyulog==0.4.0
  - qt-dotgraph==0.3.4
  - qt-gui==0.3.4
  - qt-gui-cpp==0.3.4
  - qt-gui-py-common==0.3.4
  - resource-retriever==1.12.3
  - rosapi==0.7.17
  - rosbag==1.12.7
  - rosboost-cfg==1.13.5
  - rosbridge-library==0.7.17
  - rosbridge-server==0.7.17
  - rosclean==1.13.5
  - roscreate==1.13.5
  - rosgraph==1.12.7
  - roslaunch==1.12.7
  - roslib==1.13.5
  - roslint==0.11.0
  - roslz4==1.12.7
  - rosmake==1.13.5
  - rosmaster==1.12.7
  - rosmsg==1.12.7
  - rosnode==1.12.7
  - rosparam==1.12.7
  - rospy==1.12.7
  - rosservice==1.12.7
  - rostest==1.12.7
  - rostopic==1.12.7
  - rosunit==1.13.5
  - roswtf==1.12.7
  - rqt-action==0.4.7
  - rqt-bag==0.4.7
  - rqt-bag-plugins==0.4.7
  - rqt-console==0.4.7
  - rqt-dep==0.4.7
  - rqt-graph==0.4.7
  - rqt-gui==0.3.2
  - rqt-gui-py==0.3.2
  - rqt-image-view==0.4.7
  - rqt-launch==0.4.7
  - rqt-logger-level==0.4.7
  - rqt-moveit==0.5.6
  - rqt-msg==0.4.7
  - rqt-nav-view==0.5.6
  - rqt-plot==0.4.7
  - rqt-pose-view==0.5.6
  - rqt-publisher==0.4.7
  - rqt-py-common==0.4.7
  - rqt-py-console==0.4.7
  - rqt-reconfigure==0.4.7
  - rqt-robot-dashboard==0.5.6
  - rqt-robot-monitor==0.5.6
  - rqt-robot-steering==0.5.6
  - rqt-runtime-monitor==0.5.6
  - rqt-rviz==0.5.6
  - rqt-service-caller==0.4.7
  - rqt-shell==0.4.7
  - rqt-srv==0.4.7
  - rqt-tf-tree==0.5.6
  - rqt-top==0.4.7
  - rqt-topic==0.4.7
  - rqt-web==0.4.7
  - rviz==1.12.4
  - sensor-msgs==1.12.5
  - slycot==0.2.0
  - smach==2.0.0
  - smach-ros==2.0.0
  - smclib==1.7.18
  - srdfdom==0.4.2
  - tf==1.11.8
  - tf-conversions==1.11.8
  - tf2-geometry-msgs==0.5.15
  - tf2-kdl==0.5.15
  - tf2-py==0.5.15
  - tf2-ros==0.5.15
  - topic-tools==1.12.7
  - transforms3d==0.3
  - urdfdom-py==0.3.3
  - xacro==1.11.2
prefix: /home/jgoppert/anaconda3/envs/px4

